### ISSUE TITLE
[Sui] emit event when burn Movescription

### ISSUE THREAD

**Issue by jolestar** [movescriptions/movescriptions#45]
Add a message when burn Movescription

**Comment by RandyPen** [comment]
Option\<vector\<u8\>\> as input parameters?

**Comment by jolestar** [comment]
> Option<vector<u8>> as input parameters?

yes

**Comment by pause125** [comment]
How about adding another input parameter `Option<address>`, which used to indicate for whom to burn?

**Comment by jolestar** [comment]
Maybe we need to give the burner an NFT receipt for the burn.
